//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiboardEditor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigiboardEntities : DbContext
    {
        public DigiboardEntities()
            : base("name=DigiboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnouncementsNote> AnnouncementsNotes { get; set; }
        public virtual DbSet<AnnouncementsPDF> AnnouncementsPDFs { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLogHistory> UserLogHistories { get; set; }
        public virtual DbSet<Timer> Timers { get; set; }
    }
}
