//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiboardEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timer
    {
        public int TimerID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime StopTime { get; set; }
        public bool isDeleted { get; set; }
    }
}
