//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiboardEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AnnouncementsNotes = new HashSet<AnnouncementsNote>();
            this.AnnouncementsPDFs = new HashSet<AnnouncementsPDF>();
            this.Events = new HashSet<Event>();
            this.UserLogHistories = new HashSet<UserLogHistory>();
        }
    
        public int UserID { get; set; }
        public string fullName { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public byte[] password { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isNewUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnouncementsNote> AnnouncementsNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnouncementsPDF> AnnouncementsPDFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogHistory> UserLogHistories { get; set; }
    }
}
